name = "Sleepshatter"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c824e415c5a5fd423771286cd0402a114274588f5a37233cf76387c3c54a14a"

[versions]
forge = "47.4.12"
minecraft = "1.20.1"
unsup = "1.2.0-pre3"

[options]
datapack-folder = "config/paxi/datapacks"
