name = "Sleepshatter"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b73079f1cf6cf067ca40f22b4e299d24b210c2dd59ae9ab862280a87dd38d4d6"

[versions]
forge = "47.4.12"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
