name = "Sleepshatter"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "625ed1d2a3d180ed32228844e93f4b85019d45e80f9f30a69b10b1b33ed937ed"

[versions]
forge = "47.4.12"
minecraft = "1.20.1"
unsup = "1.2.0-pre3"

[options]
datapack-folder = "config/paxi/datapacks"
