name = "Sleepshatter"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "193c0c1e04750d5cd54696ba3b35ea81dc56cab6ebf5cb906056bbaa6a5143a2"

[versions]
forge = "47.4.12"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
